Repository PrivateAIM/hub-python-client, pull requests merged in 2025-04, with the labels that each got.

#8 Fix package name in README
  README.md
Labels: documentation

#10 Add submodule that exports models used for validation
  README.md
  flame_hub/__init__.py
  flame_hub/models.py
Labels: enhancement

#13 Bump version to 0.1.3
  pyproject.toml
Labels: enhancement

#17 Fix optional fields on Project and Analysis resource
  flame_hub/_core_client.py
  tests/test_core.py
  tests/test_flow.py
Labels: bug, enhancement

#18 Add basic support for include params
  flame_hub/_base_client.py
  tests/test_base_client.py
Labels: enhancement

#19 Minor improvements
  flame_hub/_auth_client.py
  flame_hub/_auth_flows.py
  flame_hub/_base_client.py
  flame_hub/_core_client.py
  flame_hub/_exceptions.py
  flame_hub/_storage_client.py
  tests/conftest.py
  tests/test_auth.py
Labels: enhancement

#20 Extend auth resources
  flame_hub/_auth_client.py
  flame_hub/models.py
  tests/test_auth.py
Labels: enhancement

#21 Add registry projects endpoint
  flame_hub/_core_client.py
  flame_hub/models.py
  tests/test_core.py
Labels: enhancement

#22 Master image event logs
  flame_hub/_core_client.py
  flame_hub/models.py
  tests/test_core.py
Labels: enhancement

#23 Add include support for storage client
  flame_hub/_base_client.py
  flame_hub/_storage_client.py
  tests/test_storage.py
Labels: enhancement
